version: '3'
services:
    app:
        image: "levsvalov/lab4_pyapp"
        ports:
            - "8080:8080"
    redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
    nginx:
        image: "nginx:alpine"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/www/media
        depends_on: 
            - app
        ports:
            - "80:80"
    
